spring:
  application:
    name: integration-yandex
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8889/}



springdoc:
  api-docs:
    path: /api-docs
server:
  port: 8085
