version: '3'

services:
  config:
    container_name: config-service
    image: ghcr.io/diploma-atm/config_service:test
    volumes:
      - ./config-data:/var/config-data
    environment:
      - CONFIG_FOLDER=/var/config-data
    ports:
      - 8889:8888
  discovery:
    image: ghcr.io/diploma-atm/discovery_service:test
    ports:
      - 8761:8761
    depends_on:
      - config